# Generated by Django 6.0.1 on 2026-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/business/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='seller_docs/tax/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
