# Generated by Django 6.0.1 on 2026-03-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='productimages/'),
        ),
    ]
