# Generated by Django 6.0.3 on 2026-03-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0002_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.discount'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.offer'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
